/** Autogenerated Main.cpp. */

// =================================| Include only the DSP files  |=================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ===========================| Now we can add the rest of the codebase |===========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =======================================| Project Factory |=======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ----------------------------------------------------------------------
		
		registerPolyNode<project::Wavefolder<1>, scriptnode::wrap::illegal_poly<project::Wavefolder<1>>>();
		registerPolyNode<project::tank<1>, scriptnode::wrap::illegal_poly<project::tank<1>>>();
		registerPolyNode<project::shift<1>, scriptnode::wrap::illegal_poly<project::shift<1>>>();
		registerPolyNode<project::Lpf<1>, scriptnode::wrap::illegal_poly<project::Lpf<1>>>();
		registerPolyNode<project::Hpf<1>, scriptnode::wrap::illegal_poly<project::Hpf<1>>>();
		registerPolyNode<project::Hpd<1>, scriptnode::wrap::illegal_poly<project::Hpd<1>>>();
		registerPolyNode<project::gr2<1>, scriptnode::wrap::illegal_poly<project::gr2<1>>>();
		registerPolyNode<project::gr1<1>, scriptnode::wrap::illegal_poly<project::gr1<1>>>();
		registerPolyNode<project::comb<1>, scriptnode::wrap::illegal_poly<project::comb<1>>>();
		registerPolyNode<project::bpf<1>, scriptnode::wrap::illegal_poly<project::bpf<1>>>();
		registerPolyNode<project::FeedJ<1>, wrap::illegal_poly<project::FeedJ<1>>>();
		registerPolyNode<project::Filter<1>, wrap::illegal_poly<project::Filter<1>>>();
		registerPolyNode<project::gransect<1>, wrap::illegal_poly<project::gransect<1>>>();
		registerPolyNode<project::mod<1>, wrap::illegal_poly<project::mod<1>>>();
		registerPolyNode<project::PolyGrain<1>, wrap::illegal_poly<project::PolyGrain<1>>>();
		registerPolyNode<project::Pshift<1>, wrap::illegal_poly<project::Pshift<1>>>();
		registerPolyNode<project::spacer1<1>, wrap::illegal_poly<project::spacer1<1>>>();
		registerPolyNode<project::spacer2<1>, wrap::illegal_poly<project::spacer2<1>>>();
		registerDataNode<project::delStage_networkdata>();
		registerDataNode<project::gransect2_networkdata>();
		registerDataNode<project::inout4_networkdata>();
		registerDataNode<project::inout5_networkdata>();
		registerDataNode<project::input3_networkdata>();
		registerDataNode<project::InputRoute_networkdata>();
		registerDataNode<project::inputroute2_networkdata>();
		registerDataNode<project::io2_networkdata>();
		registerDataNode<project::io3_networkdata>();
		registerDataNode<project::io4_networkdata>();
		registerDataNode<project::io5_networkdata>();
		registerDataNode<project::io6_networkdata>();
		registerDataNode<project::ModIn_networkdata>();
		registerDataNode<project::rout_networkdata>();
		registerDataNode<project::Routing_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


