/** Autogenerated Main.cpp. */

// =================================| Include only the DSP files  |=================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ===========================| Now we can add the rest of the codebase |===========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =======================================| Project Factory |=======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ----------------------------------------------------------------------
		
		registerPolyNode<project::Wavefolder<1>, scriptnode::wrap::illegal_poly<project::Wavefolder<1>>>();
		registerPolyNode<project::tank<1>, scriptnode::wrap::illegal_poly<project::tank<1>>>();
		registerPolyNode<project::shift<1>, scriptnode::wrap::illegal_poly<project::shift<1>>>();
		registerPolyNode<project::gr2<1>, scriptnode::wrap::illegal_poly<project::gr2<1>>>();
		registerPolyNode<project::gr1<1>, scriptnode::wrap::illegal_poly<project::gr1<1>>>();
		registerPolyNode<project::comb<1>, scriptnode::wrap::illegal_poly<project::comb<1>>>();
		registerPolyNode<project::delStage<1>, wrap::illegal_poly<project::delStage<1>>>();
		registerPolyNode<project::gransect<1>, wrap::illegal_poly<project::gransect<1>>>();
		registerPolyNode<project::gransect2<1>, wrap::illegal_poly<project::gransect2<1>>>();
		registerPolyNode<project::spacer2<1>, wrap::illegal_poly<project::spacer2<1>>>();
		registerDataNode<project::ModIn_networkdata>();
		registerDataNode<project::PolyGrain_networkdata>();
		registerDataNode<project::spacer1_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


